### ISSUE TITLE
suggestion the <style> and  attribute "style"

### ISSUE THREAD

**Issue by nenge123** [MirazMac/html-sanitizer#1]
if i allow style tag ,but it's nothing output.

but i replace $html->nodeValue \n\s* it will output

------
base whitelist suggest 

can support "style" attribute ,and remove position .

support style tag, add scoped

but remove "html body header footer nav  * " or only keep "p span div ul li b ...allowTag "
and "position" attribute

**Comment by MirazMac** [comment]
I don't quite understand what you're trying to accomplish.
Please provide the following:

1. The code you're using
2. The output you're getting
3. The output you're expecting.

Thanks.

**Comment by nenge123** [comment]
> I don't quite understand what you're trying to accomplish.
> 
> Please provide the following:
> 
> 
> 
> 1. The code you're using
> 
> 2. The output you're getting
> 
> 3. The output you're expecting.
> 
> 
> 
> Thanks.

1. See the output of the WYSIWYG editor, and the user submits HTML security output.

2. The code contains inline style code, but the position attributes need to be filtered.

3. Blocks of code that may contain class, <pre class='language-php'>

**Comment by MirazMac** [comment]
Sorry but filtering attributes with styles or sanitizing inline styles isn't supported yet. As CSS is a completely different language. This library primarily focuses on keeping only the required HTML tags and attributes and stripping everything else. I will think about implementing it in the future. Thanks.

**Comment by nenge123** [comment]
> Sorry but filtering attributes with styles or sanitizing inline styles isn't supported yet. As CSS is a completely different language. This library primarily focuses on keeping only the required HTML tags and attributes and stripping everything else. I will think about implementing it in the future. Thanks. 

Looking forward to it😚

**Comment by MirazMac** [comment]
I'll try to implement it when I'm free. Thanks for your suggestion. Closing this for now.
